Fix compilation error in tests due to unrecognized compiler flag
Error raised:
  gnatgcc: error: unrecognized command line option ‘-fcallgraph-info=su,da’

When using:
gnatgcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0

Tests:
Total Tests Run:   30
Successful Tests:  30
Failed Assertions: 0
Unexpected Errors: 0